### ISSUE TITLE
问一下后端原理

### ISSUE THREAD

**Issue by Jannchie** [ProtossProbe/bilicount#3]
后端是代理请求b站api吧，注意到大概5秒更新一次数据，据我所知这个api是有限速的。。5秒一次更新的话，感觉十几个人同时访问就凉凉了，有用到什么反爬手段嘛？

**Comment by ProtossProbe** [comment]
后端是朋友帮忙写的，我完全不懂后端......没有任何反爬手段，所以一旦这个网站访问量过大频率过快就会停止服务一段时间（一般是一两天好像），只要知道的人少就暂且不会出现这个问题......（
